language: android
script: "./gradlew build test"
deploy:
  provider: releases
  api_key: $GITHUB_DEPLOY_OAUTH_TOKEN
  file: app/build/outputs/apk/app-release-unsigned.apk
  skip_cleanup: true
  on:
    tags: true
android:
  components:
    - platform-tools
    - android-23
    - build-tools-23.0.1
